//app-config.js - generated by MarkLogic Appbuilder 2.0 2015-07-06T17:33:59.797607-04:00
var sidebar_config=
{"facets":
{ "season_number":
		{"name":"season_number", "type":"range", "options":
			{"order":"item-order", "direction":"descending", "limit":"10"
			}, 
		 "fragment-scope":"", "label":"Season", "front-page":"true", "side-bar":"true", "datatype":
		 	{"collation":"http://marklogic.com/collation/", "_value":"xs:string"
		 	}, 
		  "qnames":
		  	{"type":"element/attribute", "elem-ns":"", "elem":"span", "attr-ns":"", "attr":"character", "field":""
		  	}, 
		  "collection-prefix":"", "facet":
		  	{"enabled":"true", "options":
		  		{"order":"frequency-order", "direction":"ascending", "limit":"10"
		  		}
		  	}, 
		  "term-options":
		  	{"case":"", "punct":"punctuation-insensitive", "wild":"", "stem":"", "diacritic":""
		  	}, 
		  "absolute-buckets":
		  	{"use":"false", "bucket":[
		  		{"anchor":"", "lt":"", "ge":"", "name":""
		  		}]
		  	}, "relative-buckets":
		  		{"use":"false", "bucket":[
		  			{"anchor":"", "lt":"", "ge":"", "name":""
		  			}]
		  		}
		  	}, 	
	"character":
		{"name":"character", "type":"range", "options":
			{"order":"item-order", "direction":"descending", "limit":"10"
			}, 
		 "fragment-scope":"", "label":"Character", "front-page":"true", "side-bar":"true", "datatype":
		 	{"collation":"http://marklogic.com/collation/", "_value":"xs:string"
		 	}, 
		  "qnames":
		  	{"type":"element/attribute", "elem-ns":"", "elem":"span", "attr-ns":"", "attr":"character", "field":""
		  	}, 
		  "collection-prefix":"", "facet":
		  	{"enabled":"true", "options":
		  		{"order":"frequency-order", "direction":"ascending", "limit":"10"
		  		}
		  	}, 
		  "term-options":
		  	{"case":"", "punct":"punctuation-insensitive", "wild":"", "stem":"", "diacritic":""
		  	}, 
		  "absolute-buckets":
		  	{"use":"false", "bucket":[
		  		{"anchor":"", "lt":"", "ge":"", "name":""
		  		}]
		  	}, "relative-buckets":
		  		{"use":"false", "bucket":[
		  			{"anchor":"", "lt":"", "ge":"", "name":""
		  			}]
		  		}
		  	}, "episode_name":
		  		{"name":"episode_name", "type":"range", "options":
		  			{"order":"frequency-order", "direction":"descending", "limit":"10"
		  			}, 
		  		"fragment-scope":"", "label":"Episode", "front-page":"true", "side-bar":"true", "datatype":
		  			{"collation":"http://marklogic.com/collation/", "_value":"xs:string"
		  			}, 
		  		"qnames":
		  			{"type":"element/attribute", "elem-ns":"", "elem":"episode_name", "attr-ns":"", "attr":"", "field":""
		  			}, 
		  		"collection-prefix":"", "facet":
		  			{"enabled":"true", "options":
		  				{"order":"frequency-order", "direction":"descending", "limit":"10"
		  				}
		  			},
		  		 "term-options":
		  		 	{"case":"", "punct":"punctuation-insensitive", "wild":"", "stem":"", "diacritic":""
		  		 	}, 
		  		 "absolute-buckets":
		  		 	{"use":"false", "bucket":[
		  		 		{"anchor":"", "lt":"", "ge":"", "name":""
		  		 		}]
		  		 	}, "relative-buckets":
		  		 		{"use":"false", "bucket":[
		  		 			{"anchor":"", "lt":"", "ge":"", "name":""
		  		 			}]
		  		 		}
		  		 	}, "episode_number":
		  		 		{"name":"episode_number", "type":"range", "options":
		  		 			{"order":"frequency-order", "direction":"descending", "limit":"10"
		  		 			}, 
		  		 		"fragment-scope":"", "label":"Episode Number", "front-page":"false", "side-bar":"true", "datatype":
		  		 			{"collation":"", "_value":"xs:int"
		  		 			}, 
		  		 		"qnames":
		  		 			{"type":"element/attribute", "elem-ns":"", "elem":"episode_number", "attr-ns":"", "attr":"", "field":""
		  		 			}, 
		  		 		"collection-prefix":"", "facet":
		  		 			{"enabled":"true", "options":
		  		 				{"order":"frequency-order", "direction":"descending", "limit":"10"
		  		 				}
		  		 			}, "term-options":
		  		 				{"case":"", "punct":"punctuation-insensitive", "wild":"", "stem":"", "diacritic":""
		  		 				}, "absolute-buckets":
		  		 					{"use":"false", "bucket":[
		  		 						{"anchor":"", "lt":"", "ge":"", "name":""
		  		 						}]
		  		 					}, "relative-buckets":
		  		 						{"use":"false", "bucket":[
		  		 							{"anchor":"", "lt":"", "ge":"", "name":""
		  		 							}]
		  		 						}
		  		 					},  "timestamp":{"name":"timestamp", "type":"range", "options":{"order":"item-order", "direction":"descending", "limit":"10"}, "fragment-scope":"", "label":"Point In Time", "front-page":"false", "side-bar":"true", "datatype":{"collation":"", "_value":"xs:int"}, "qnames":{"type":"element/attribute", "elem-ns":"", "elem":"timestamp", "attr-ns":"", "attr":"", "field":""}, "collection-prefix":"", "facet":{"enabled":"true", "options":{"order":"item-order", "direction":"descending", "limit":"10"}}, "term-options":{"case":"", "punct":"punctuation-insensitive", "wild":"", "stem":"", "diacritic":""}, "absolute-buckets":{"use":"true", "bucket":[{"anchor":"", "lt":"799", "ge":"0", "name":"Beginning", "_value":"Act I"}, {"anchor":"", "lt":"1599", "ge":"800", "name":"Middle", "_value":"Act II"}, {"anchor":"", "lt":"2700", "ge":"1600", "name":"End", "_value":"Act III"}]}, "relative-buckets":{"use":"false", "bucket":[{"anchor":"", "lt":"", "ge":"", "name":""}]}}}}


var results_config=
{"metadata":
	{"sort":
		{"relevance":
			{"position":"1", "label":"Relevance", "order":
				{"direction":"descending", "type":"score", "datatype":"", "collation":"", "elem-ns":"", "elem":"", "attr-ns":"", "attr":"", "field":""
				}
			}, "season_number":
			{"position":"2", "label":"Season", "order":
				{"direction":"descending", "type":"score", "datatype":"", "elem-ns":"", "elem":"", "attr-ns":"", "attr":"", "field":""}
				}
			}, "columns":[
				{"abstract-title":[
					{"position":"1", "type":"value", "elem":"sub_content", "attr":""
					}], "abstract-snippet":[
						{"position":"1", "type":"value", "elem":"episode_title", "attr":""
						}], "abstract-metadata":[
						{"position":"1", "type":"literal", "text":"Season "
						}, 
						{"position":"2", "type":"value", "elem":"season_number", "attr":""
						}]
					}]
				}
			}


var controller_config={
		appWrapper: "body",
		widgetClass: ".widget",
		version: "v1", // version number of the REST API
		proxy: false, // proxy url - defaults to false for no proxy
		optionsNode: "all",
		queryPage: 1,
		pageLength: 20,
		useShadows: true, // global toggle for shadow queries
		enableBookmarking: true, // toggle for bookmarking suppport
		bookmarkingDelimiters: ["*_*", "*__*"] // delimiters to be used while encoding url bookmarks
	}
var pie_config_1 = { constraint:"character", constraintType: "range-unbucketed", dataType:"xs:string", dataLabel:null, measureLabel:null };
var bar_config_2 = { constraint: "season_number", constraintType: "range-unbucketed", dataType:"xs:int", title: "Season", dataLabel: null, measureLabel:null };





